# Generated by Django 4.0.3 on 2022-04-14 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profileapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='messaage',
            new_name='message',
        ),
    ]
