<<<<<<< HEAD
# Generated by Django 3.2.12 on 2022-05-24 20:30
=======
# Generated by Django 3.2.12 on 2022-05-24 11:29
>>>>>>> dd7c4103fb3f1bbcba0a0c266fc7a192bbe5f3da

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('birthday', models.DateField(null=True)),
                ('profile', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Boxoffice',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('movieNm', models.CharField(max_length=100)),
                ('rank', models.IntegerField()),
                ('audiAcc', models.IntegerField()),
                ('independent', models.BooleanField()),
                ('poster_path', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Director',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('birthday', models.DateField(null=True)),
                ('profile', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
<<<<<<< HEAD
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, null=True)),
                ('adult', models.BooleanField(default=False, null=True)),
                ('independent', models.BooleanField(null=True)),
                ('release_date', models.TextField(null=True)),
                ('overview', models.TextField(null=True)),
                ('poster_path', models.TextField(null=True)),
                ('original_language', models.CharField(max_length=10, null=True)),
                ('genres', models.CharField(max_length=30, null=True)),
                ('vote_average', models.FloatField(null=True)),
                ('runtime', models.IntegerField(null=True)),
                ('ott_service', models.CharField(max_length=100, null=True)),
                ('backdrops', models.TextField(null=True)),
                ('actors', models.ManyToManyField(null=True, related_name='act_movie', to='movies.Actor')),
                ('directors', models.ManyToManyField(null=True, related_name='direct_movie', to='movies.Director')),
                ('like', models.ManyToManyField(null=True, related_name='like_movie', to=settings.AUTH_USER_MODEL)),
                ('playlist', models.ManyToManyField(null=True, related_name='playlist_movie', to=settings.AUTH_USER_MODEL)),
                ('watch', models.ManyToManyField(null=True, related_name='watch_movie', to=settings.AUTH_USER_MODEL)),
=======
                ('tmdb_id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('adult', models.BooleanField(default=False)),
                ('independent', models.BooleanField()),
                ('release_date', models.DateField()),
                ('overview', models.TextField()),
                ('poster_path', models.TextField()),
                ('genre_ids', models.CharField(max_length=30)),
                ('vote_average', models.FloatField()),
                ('ott_service', models.CharField(max_length=100)),
                ('backdrops', models.TextField()),
                ('actors', models.ManyToManyField(related_name='act_movie', to='movies.Actor')),
                ('directors', models.ManyToManyField(related_name='direct_movie', to='movies.Director')),
                ('like', models.ManyToManyField(related_name='like_movie', to=settings.AUTH_USER_MODEL)),
                ('playlist', models.ManyToManyField(related_name='playlist_movie', to=settings.AUTH_USER_MODEL)),
                ('watch', models.ManyToManyField(related_name='watch_movie', to=settings.AUTH_USER_MODEL)),
>>>>>>> dd7c4103fb3f1bbcba0a0c266fc7a192bbe5f3da
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('rate', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('like', models.ManyToManyField(related_name='like_review', to=settings.AUTH_USER_MODEL)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='movies.movie')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Hashtag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=100)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hashtag', to='movies.movie')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hashtag', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
