# Generated by Django 3.2.12 on 2022-05-23 03:40

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='using_ott',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('넷플릭스', '넷플릭스'), ('왓챠', '왓챠'), ('디즈니+', '디즈니+'), ('웨이브', '웨이브')], max_length=16),
        ),
    ]
